team-wedding/back-end

schema.sql
> Schema 정의 파일을 추가하였습니다. 해당 파일은 노션에 제가 정리한 import 방법 참고하셔서 각자 로컬에 import 하시면 될 것 같아요!
=> chore: schema 파일 추가

schema.sql
> 12/13일 기준 기능 요구사항 수정한 내용을 토대로 테이블 수정된 것을 반영하여 schema 파일을 수정하였습니다
=> fix: schema 파일 수정

src/app.js, src/controllers/invitationController.js, src/repositories/invitationRepository.js, src/routes/invitationRouter.js, src/services/invitationService.js
> 청첩장 기능 구현 시 필요한 기본 구조들을 user를 참고하여 생성하였습니다.
=> chore: 청첩장 관련 기본 구조 생성

src/models/guestInfo.js, src/models/index.js, src/models/invitation.js
> invitation과 guestInfo 테이블을 참고하여 models를 추가하였습니다.
> invitation과 guestInfo model을 생성하고 src/models/index.js에 FK 연결을 위한 ORM 관계 설정 코드를 추가하였습니다. 혹시 잘못된 부분이 있다면 말씀해 주시면 감사하겠습니다:)
=> feat: invitation, guestInfo models 추가

src/controllers/invitationController.js, src/repositories/invitationRepository.js, src/routes/invitationRouter.js, src/services/invitationService.js
=> feat: invitation 기능 구현

src/middlewares/authToken.js, src/models/invitation.js, src/services/invitationService.js
> 청첩장 기능에서 오류가 발생하여 기존의 코드 오류를 수정하였습니다. 추가적으로 토큰의 userId 값을 받아와서 req에 사용하도록 authToken에 일부 코드를 추가하였습니다
=> fix: invitation 수정

src/controllers/invitationController.js, src/middlewares/authToken.js, src/services/invitationService.js
> 청첩장 등록 기능 시 userId를 body에 포함시키지 않고 헤더의 토큰값에서 userId를 추출하여 자동으로 body에 포함시키도록 기능을 수정하였습니다.
=> fix: 청첩장 등록 기능 수정

src/models/invitation.js, src/repositories/invitationRepository.js
> invitation 테이블에 일부 column을 추가함에 따라 일부 코드를 수정했습니다
=> fix: invitation 테이블 수정

src/controllers/invitationController.js, src/repositories/invitationRepository.js, src/services/invitationService.js
> 청첩장 수정, 삭제 기능의 토큰 관련 오류 발생 부분을 해결하였습니다
=> fix: invitation 수정, 삭제 기능 수정

config/config.ts, src/app.ts, src/models/index.ts
> ts로 변경함에 앞서 공통 컴포넌트(app.ts, models / index.ts, config / config.ts)를 생성 및 작성하여 업로드 하였습니다
=> chore: 공통 컴포넌트 ts 파일 생성

src/controllers/attendanceController.ts, src/interfaces/attendanceData.ts, src/models/guestInfo.ts, src/repositories/attendanceRepository.ts, src/routes/attendanceRouter.ts, src/services/attendanceSerivce.ts
Merge pull request #16 from team-wedding/feature/attendance-ts
chore : attendance 기능 ts 파일 생성
=> chore: attendance 기능 ts 파일 생성

src/models/index.ts, src/models/invitation.ts
>API 테스트 시 guest_info 테이블과 invitation 테이블간의 fk 에러를 해결하였습니다.
=> fix: invitation fk 에러 수정

.gitignore, config/nodemailerConfig.ts, package-lock.json, package.json, src/controllers/userController.ts, src/middlewares/authToken.ts, src/middlewares/validations.ts, src/routes/userRouter.ts, src/services/userService.ts
> nodemailer 모듈을 활용한 임시 비밀번호 발급 API 구현
> 경로 : account/password/reset
> req.body : email 값 필요
=> Feat: 임시 비밀번호 발급 API 구현

src/controllers/celebrationMsgController.ts, src/interfaces/celebrationMsg.interface.ts, src/models/celebrationMsg.ts, src/repositories/celebrationMsgRepository.ts, src/routes/celebrationMsgRouter.ts, src/services/celebrationMsgService.ts
- celebrationMsg 축하메세지(포토톡) 기능 구현 및 연결(controller, service, repository, router)
- api는 축하 메세지 전체 조회, 개별 조회, 개별 등록, 개별 수정, 개별 삭제로 총 5가지.
=> Feat: celebrationMsg(축하메세지) 기능 비즈니스 로직 구현

src/app.ts, src/controllers/userController.ts
> CORS 접근 가능 url 추가
>로그인, 회원탈퇴 API 요청 성공 후 쿠키삭제 로직 추가
=> Fix : CORS 재설정 및 로그인, 회원탈퇴 API 로직 변경

package-lock.json, package.json, src/app.ts, src/controllers/userController.ts, src/middlewares/authToken.ts, src/middlewares/imageUploader.ts, src/routes/userRouter.ts, src/services/userService.ts
> AWS S3와 연동된 imageUploader 미들웨어 구현
=> Feat: AWS S3 활용 imageUploader 미들웨어 구현

src/controllers/attendanceController.ts, src/repositories/attendanceRepository.ts, src/services/attendanceService.ts
- 통계(참석) 관련 api
: 전체 참석 조회 api에서 pagination 기능(전체 데이터를 페이지에 분할하여 보여주는 기능) 추가하여 관련 파일들 수정했습니다.
- 이후 celebrationMsg 전체 참석 조회 코드도 수정할 예정입니다.
=> feat: attendance 전체 참석 조회 pagination 구현

src/controllers/attendanceController.ts, src/controllers/celebrationMsgController.ts, src/repositories/attendanceRepository.ts, src/repositories/celebrationMsgRepository.ts, src/services/attendanceService.ts, src/services/celebrationMsgService.ts
- 포토톡(축하 메세지) 관련 api
: 전체 축하 메세지 조회 api에서 pagination 기능(전체 데이터를 페이지에 분할하여 보여주는 기능) 추가하여 관련 파일들 수정했습니다.
=> feat: celebrationMsg 전체 축하메세지 조회 pagination 구현

src/controllers/celebrationMsgController.ts, src/models/celebrationMsg.ts, src/routes/celebrationMsgRouter.ts
- 개인 축하메세지 등록
S3에 이미지 올리는 코드 추가 -> 수정과 삭제기능 곧 추가할 예정
=> feat: 개인 축하메세지 등록에서 S3에 이미지 올리는 코드 추가

src/interfaces/account.interface.ts, src/interfaces/calendar.interface.ts, src/interfaces/contact.interface.ts, src/interfaces/gallery.interface.ts, src/interfaces/invitation.interface.ts, src/interfaces/map.interface.ts, src/interfaces/notice.interface.ts, src/models/account.ts, src/models/calendar.ts, src/models/contact.ts, src/models/gallery.ts, src/models/invitation.ts, src/models/map.ts, src/models/notice.ts
> 청첩장 API가 일부 수정되어 invitation과 선택 테이블들의 각 interface와 model 코드를 수정하였습니다
=> invitation 테이블 수정

package-lock.json, package.json, src/app.ts, src/controllers/imageUploadController.ts, src/routes/celebrationMsgRouter.ts, src/routes/imageUploadRouter.ts, src/utils/imageUploader.ts
> 프론트랑 의논 결과 S3 이미지 업로드 api를 따로 생성하였습니다
> 기존에 희범님이 middleware로 선언하신 코드를 utils 폴더로 옮기고 라우터, 컨트롤러 설정을 통해 이미지 업로드 api를 따로 생성하였습니다
> 기존에 지현님이 구현하신 축하 메세지 S3 업로드 기능은 다시 삭제하셔도 될 것 같습니다
=> 이미지 업로드 api 생성

src/controllers/imageUploadController.ts
> imageUploadController의 코드를 일부 수정하였습니다
=> fix: 이미지 업로드 코드 일부 수정

src/controllers/imageUploadController.ts
> 프론트 요청사항으로 이미지 업로드 api의 res에서 message 값을 삭제하였습니다
=> 이미지 업로드 api res 형태 수정

src/controllers/celebrationMsgController.ts, src/models/celebrationMsg.ts, src/routes/celebrationMsgRouter.ts
S3 이미지 업로드하는 api가 새로 만들어져서
기존의 개별 축하메세지 등록 api에서 S3 imageUpload 기능 삭제했습니다.
=> Fix: 개별 축하메세지 등록 기능에서 S3 imageUpload 기능 삭제

.gitignore, src/app.ts, src/models/index.ts, src/services/userService.ts
> 비밀번호 초기화 시 생성되는 임시 비밀번호 규칙 수정
(문자+숫자 10자 -> 문자+숫자+특수기호 16자)
> DB 테이블 관계 추가
(user & token : 1대1관계, FK)
=> Fix: 임시 비밀번호 규칙 수정, 테이블 관계 추가(user, token)

src/controllers/celebrationMsgController.ts, src/interfaces/celebrationMsg.interface.ts, src/models/celebrationMsg.ts, src/services/celebrationMsgService.ts
> 포토톡 등록 api에 이미지 갯수 10개 제한 기능을 추가했습니다
> imageUrl 값의 갯수가 10개 초과할 시 400 에러가 발생하도록 구성하였습니다
=> fix: celebraionMsg 이미지 갯수 제한 추가 기능 추가

src/repositories/attendanceRepository.ts
pagination 할 때 완전한 전체 참석 여부가 조회 되는 문제 수정함.
(size = 2여서 한 페이지에 2개가 떠야 되는데 전체가 다 바뀌는 문제)
=> Fix: 전체 참석 조회 중 pagination 조회 오류 수정

src/controllers/attendanceController.ts, src/repositories/attendanceRepository.ts, src/services/attendanceService.ts
=> Fix: 전체 참석 정보 조회 + pagination 오류 수정

src/utils/imageUploader.ts
=> fix: S3 img 형태 수정

src/controllers/invitationController.ts, src/models/invitation.ts, src/services/invitationService.ts, src/utils/error.ts
> 청첩장 등록 및 수정의 전반적인 API 수정 사항을 반영했습니다.
> 청첩장 model의 속성을 수정하고 controller, service 부분에 유효성 검사 로직을 추가했습니다.
=> Add: 청첩장 수정 유효성 검사 로직 추가

src/controllers/invitationController.ts
> 청첩장 등록 API의 res 형식에 등록한 청첩장의 id를 반환하는 내용을 추가했습니다.
=> fix: 청첩장 등록 res 형식 수정

src/controllers/s3Controller.ts, src/routes/s3Router.ts
> 청첩장의 갤러리와 포토톡 이미지 s3 수정 API를 구현하였습니다. 
> 두 API는 배열 값으로 선언되어있기 때문에 parmas에 index값을 할당하여 db에 접근하도록 설정했습니다.
> API 실행 방법은 팀 우결 노션 / 개발 문서 / 백엔드 / S3 이미지 관리에 작성해놓았으니 참고하셔서 실행하시면 됩니다!
=> add: 갤러리, 포토톡 s3 이미지 수정 API 구현

config/swagger.ts, package-lock.json, package.json, src/app.ts, src/routes/attendanceRouter.ts, src/routes/celebrationMsgRouter.ts
- swagger 설정 파일 추가했습니다.
- 제가 관여한 기능에 swagger docs 주석을 추가했습니다.
- 두 분은 각자의 기능에 제가 router 코드의 앞쪽에 추가한 주석 코드를 작성하시고, swagger 링크에 들어가서 확인해보시면 됩니다.
- 저희 마지막 회의 일지에 예시 사진을 추가했으니 참고하시면 됩니다.
=> feat : swagger 문서 자동화 설정, attendances & celebrationMsgs router에 swagger 주석 추가

src/controllers/attendanceController.ts, src/controllers/celebrationMsgController.ts
- 서버 에러의 status가 잘못 작성되어 수정하였습니다.
=> refactor : http status code 수정

dist/src/app.js, dist/src/controllers/celebrationMsgController.js, dist/src/controllers/invitationController.js, dist/src/controllers/userController.js, dist/src/models/celebrationMsg.js, dist/src/models/guestInfo.js, dist/src/models/index.js, dist/src/models/invitation.js, dist/src/models/token.js, dist/src/repositories/celebrationMsgRepository.js, dist/src/repositories/invitationRepository.js, dist/src/routes/celebrationMsgRouter.js, dist/src/services/celebrationMsgService.js, dist/src/services/invitationService.js, dist/src/utils/error.js
=> Fix: dist 파일 최신화

src/app.ts
> www.woogyeol.site CORS 설정했습니다요
=> Fix: Cors 설정

package-lock.json, package.json, src/controllers/s3Controller.ts, src/routes/s3Router.ts, src/utils/s3.ts
> S3 이미지 업로드 속도의 최적화를 위해 이미지 리사이징 기능을 추가했습니다.
> 사용자가 이미지를 업로드하면 이미지를 바로 S3에 업로드하지 않고, 특정 크기로 리사이징한 후 업로드하도록 로직을 수정했습니다. 
> 현재 리사이징 크기는 450px, 포맷은 webp로 설정해놓았습니다. 테스트 해보시고 크기 및 포맷 변경이 필요하면 말씀해주세요!
> 추가적으로 sharp 모듈을 설치하여 package 파일의 수정이 있어, pull 하시고 npm i 한 번 하신 후 실행해주시면 감사하겠습니다.
=> feat: S3 이미지 업로드 리사이징 기능 추가
